services:
  db:
    image: postgres:latest
    restart: unless-stopped
    ports:
      - ${WS_DATABASE_PORT:-5432}:5432
    environment:
      POSTGRES_USER: ${WS_DATABASE_USER:-postgres}
      POSTGRES_PASSWORD: ${WS_DATABASE_PASSWORD:-postgres}
      POSTGRES_DB: ${WS_DATABASE_NAME:-postgres}
    volumes:
      - db:/var/lib/postgresql/data
  
  pgadmin:
    image: dpage/pgadmin4
    restart: unless-stopped
    ports:
      - 8081:80
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: 123456
    depends_on:
      - db
    volumes:
      - pgadmin:/var/lib/pgadmin

volumes:
  db:
    driver: local
  pgadmin:
    driver: local